INSERT INTO ORDER_RESTAURANT(ID, ORDER_DESCRIPTION, VALUE) VALUES (1, 'TESTE', 13);
INSERT INTO ORDER_RESTAURANT(ID, ORDER_DESCRIPTION, VALUE) VALUES (2, 'TESTE2', 134);
INSERT INTO ORDER_RESTAURANT(ID, ORDER_DESCRIPTION, VALUE) VALUES (3, 'TESTE3', 134);
INSERT INTO ORDER_RESTAURANT(ID, ORDER_DESCRIPTION, VALUE) VALUES (4, 'TESTE4', 134);
